### ISSUE TITLE
Is a custom QueryModifier wanted or possible?

### ISSUE THREAD

**Issue by 1letter** [collective/collective.collectionfilter#145]
@thet @agitator 
I would like manipulate the custom query in the Collectionish Collection Object. I implement, in a local branch of this package,  a hook via adapter registration. The rest of the manipulation is in my own addon.

```
# interfaces.py
class ICustomQueryModifier(Interface):
    """adapter interface for modifying the custom query"""

    def transformQuery(self, custom_query):
        """transform the query
        @return: a new custom query
        """
```

```
@implementer(ICollectionish)
class CollectionishCollection(object):
    ....
    def results(self, custom_query, request_params):

        # Hook to customize the custom_query
        qm = queryMultiAdapter((self,), ICustomQueryModifier)
        if qm is not None:
            custom_query = qm.transformQuery(custom_query)
            
        return self.collection.results(
            batch=False, brains=True, custom_query=custom_query
        )
```

My Question, is such extension needed, wanted, possible, tolerate or permitted if i make a PR with this changes?

**Comment by djay** [comment]
@thet @1letter btw I did already impliment a limited query modifier that modifies the sort only in https://github.com/collective/collective.collectionfilter/pull/136. I didn't end up using it so I should probably take it out but I can see it could be generalised to a query modifier. 
But I'm still trying to understand the usecase. Is it that you want all filters over the whole site to add additional "invisible" criteria thats not a filter portlet or in the collection?
Or you want to do something dynamic that uses some other information in the request to modify the query? if so what?

**Comment by 1letter** [comment]
Sorry for the lately response. My Goal was a custom filter, based on the portlet filter selections, for the collection of the result view. i was on a wrong way with the hook above.
I use two Collection Filter Portlets. I have three Catalog Indexes based on collective.taxonomy. A full value and a two values splitted from the full value. The Catalog Index "full_tax_value", "semester" and "course of studies".

Example:
medizin -> 1.semester -> the  "full_tax_value" in catalog is 1.1, the "semester" value is 1, the "course of studies" value is 1
medizin -> 2. semester -> the  "full_tax_value" in catalog is 1.2, the "semester" value is 1, the "course of studies" value is 2
jura -> 1.semester -> the  "full_tax_value" in catalog is 2.1, the "semester" value is 2, the "course of studies" value is 1
jura -> 2. semester -> the  "full_tax_value" in catalog is 2.1, the "semester" value is 2, the "course of studies" value is 2

The first Collection Filter Portlet contains all "course of studies"
The seconde Collection Filter Portlet contains all "semester"

In the Resultview i concat all requested "course of studies" and  "semester"  values and search in the catalog by "full_tax_value".

i didn't notice that the filterview is only for the Portlet, i thought the filterview is also for the requested collection. My mistake.
