### ISSUE TITLE
wrong filteritems with multiple contentlisting tiles on one page

### ISSUE THREAD

**Issue by petschki** [collective/collective.collectionfilter#150]
**Given Mosaic Page layout:**

```
+-----------------------+
| Contentlisting #1     |
+-----------------------+
| Filter Tile with      |
| content_selector of.  |
| Contentlisting #2.    |
+-----------------------+
| Contentlisting #2     |
+-----------------------+
```

**What I expect:**
Filter Tile has filteritems of `Contentlisting #2`

**What you get:**
Filter Tile has filteritems of `Contentlisting #1`

**Why?**
Because the `ICollectionish` adapter always sets `self.collection` of the first found contentlisting tile when initializing. See here https://github.com/collective/collective.collectionfilter/blob/master/src/collective/collectionfilter/tiles/__init__.py#L91 

**Solution:**
`self.collection` should always be set to the actual found contentlisting tile in `selectContent()` here https://github.com/collective/collective.collectionfilter/blob/master/src/collective/collectionfilter/tiles/__init__.py#L102

**Comment by djay** [comment]
from memory it has to default to the first listing tile because we have to give a default when creating the filter tile and at that stage there is no custom css selector. But I think it reevaluates which listing its using at run time by default so will use the correct one later?
