### ISSUE TITLE
Feature Request: Allow any Keyword index to selected as a groupby filter

### ISSUE THREAD

**Issue by djay** [collective/collective.collectionfilter#19]
Seems like a pain to require users to write code to handle simple cases where you don't need advanced options and some diazo can fix things like friendly text?

**Comment by djay** [comment]
Sorry, ignore this. Part of the ongoing confusion between c.portlets.collectionfilter and c.collectionfilter. I see this is already implemented. Closing.

**Comment by thet** [comment]
@djay yes, now all catalog indices are offered, except those in ``collective.collectionfilter.vocabularies.GROUPBY_BLACKLIST``.

Ref: https://github.com/collective/collective.collectionfilter/commit/0a761b1ae971375c8a49b9819b06d0222e72b176
