### ISSUE TITLE
be able to separate contentloader target/content selectors when using mosaic layout pages and collectionfilter tile

### ISSUE THREAD

**Issue by petschki** [collective/collective.collectionfilter#20]
This is what I tried:

Create a mosaic layout page with collectionfilter tile and contentlisting tile (with an extra css-class "collectionfilter-content") and try to inject the filtered collection data into it.
So the data get's loaded from the linked collection correctly but (at least I think so) cannot be placed inside the tile slot because target and content selector is the same in `reloadCollection` here:
https://github.com/collective/collective.collectionfilter/blob/master/src/collective/collectionfilter/resources/collectionfilter.js#L137-L138

So maybe I missed something and this is already possible or if not and you agree to separate the selectors in the tile settings (additional field for target selector) I'll create a pull request for this.

/cc @agitator @thet

**Comment by thet** [comment]
@petschki - don't you want to replace the same collection results with the results from the ajax call?
the ``content`` option of contentloader defines the DOM element from the AJAX call which should be used to replace the ``target`` element. Normally these are the same.

**Comment by petschki** [comment]
@thet I tried more on this but without luck ... what I try to achieve is something like this:

<img width="1283" alt="bildschirmfoto 2018-10-22 um 10 22 11" src="https://user-images.githubusercontent.com/511761/47283893-701d5e00-d5e5-11e8-9b63-76c03cafb2c8.png">

So I took the following steps:

1. enable "mosaic layout" for a page
2. add collectionfilter tiles at the top with a referenced collection
3. add contentlisting tile at the bottom (with a custom target class name) to get some initial listing (with the same settings as the referenced collection in the filter tiles)

this is - as decribed above - not possible, because the (correctly) XHR loaded and filtered collection content can not be placed inside the contentlisting tile.

So my next try was to:

1. enable "mosaic layout" for a collection
2. add collectionfilter tiles (with the collection itself as reference)
3. add contentlisting tile with extra class
4. change the "Result listing view name" of the previously added filter tile to the view of the contentlisting tile (something like `@@plone.app.standardtiles.contentlisting/8bfd66a776a74b879c438beccb667d71`)

so this now loads the content of the contentlisting tile into the contentlisting tile but without any filtering, because contentlisting tiles cannot be filtered with external request variables ... bummer.

so right now I'm stuck  ... 

The portlet approach works perfectly (as you can see here http://plone5.interreg.kombinat.at/projekte) but I really would like to enable this feature for tiles, which would make it much more flexible on the frontend side.

any hints to make this possible?

**Comment by petschki** [comment]
A bit more diving into this I've managed to get my idea to work and documented it here https://github.com/collective/collective.collectionfilter/blob/8a79ca4eb4b007c0b2d87af41de0ca69f1320bd8/README.rst#mosaic-integration ... but I think this needs some improvement to make it easier for integrators.

**Comment by petschki** [comment]
As this question is quite clearly answered to me now I've created an enhancement ticket #40 and I'll close this.
