### ISSUE TITLE
make compatible with plone 5.0.x

### ISSUE THREAD

**Issue by djay** [collective/collective.collectionfilter#23]
Seems like it would require

1. change setup.py requirement
2. own implementation of get_top_request
3. requiring c.indexing if using 5.x.

Anything else?

**Comment by agitator** [comment]
As far as I remember it was never planned to be used to run on 5.0.x, runs perfectly fine on 5.1.x

**Comment by djay** [comment]
@agitator its a potential PR from us because we need its functionality and we don't yet run on 5.1

**Comment by agitator** [comment]
ah, so 5.0.x
@thet probably knows more what's needed ;-)

**Comment by thet** [comment]
@djay 
I don't think c.indexing is needed.
The rest looks like it's what is needed.
Ping me or @agitator once you preared a PR.

**Comment by instification** [comment]
@thet @agitator have submitted a PR for 5.0.x compatibility
