### ISSUE TITLE
activate tests on travis-ci.org

### ISSUE THREAD

**Issue by petschki** [collective/collective.collectionfilter#36]
I do not have rights to activate this on travis-ci.org ... strange because the last pull request was tested somehow ... maybe because I've forked it to my personal github user ... can anybody activate this on collective repo?

/cc @thet @agitator

<img width="695" alt="Bildschirmfoto 2019-03-25 um 10 36 35" src="https://user-images.githubusercontent.com/511761/54909324-3335fa00-4eea-11e9-8570-451ed761efb7.png">

**Comment by thet** [comment]
done: 
![Screenshot_2019-03-25 collective collective collectionfilter - Travis CI](https://user-images.githubusercontent.com/170891/54910542-d4be4b00-4eec-11e9-8bc8-d2dc1ca718f4.png)
