### ISSUE TITLE
2.x branch/releases

### ISSUE THREAD

**Issue by instification** [collective/collective.collectionfilter#38]
I see that for 3.x support for Plone 5.0.x has been dropped in 3.x, presumably because it is too much work to support with new features etc.

Is it possible to create a 2.x branch and releases so that we can maintain a 5.0.x compatible product. It is unlikely we'll be keeping it up to date with master, but we can make bug fixes as necessary for the current feature set to work in 5.0.x

I'm happy to create & maintain the 2.x branch if someone with permission is happy to make releases, or give me permission to release to pypi.

**Comment by petschki** [comment]
done ... unfortunately I do not have permissions on pypi too but pinging @thet @agitator or @jensens is fast according to experience 😉

**Comment by jensens** [comment]
@instification whats your PyPI username?

**Comment by instification** [comment]
hi @jensens it's the same as here - instification

**Comment by djay** [comment]
This seems like the wrong way to go to me. Looking at the changes needed to main 5.0.x they minimal and trying to fix so many bugs in a fork is creating a lot of pain

**Comment by jensens** [comment]
@djay, well, I think it is upon the maintainers/ authors to decide if they want to support outdated versions. Or did I get you wrong and you will help to support the old Plone version in current master?
