### ISSUE TITLE
Incorrect count on "all" when "Narrow down filter options" enabled and viewing a filtered result

### ISSUE THREAD

**Issue by pigeonflight** [collective/collective.collectionfilter#42]
This is known to affect branch 2.x on Plone 5.0.x

## How to replicate
Create a keyword portlet and ensure that "show count" and  "Narrow down filter options" is enabled.

### expected behaviour
The All count should not change as you click on keywords

### actual behaviour
The All count changes to match the count of the active query.

![collectionfilter-al](https://user-images.githubusercontent.com/31827/55470349-0c07b880-55cd-11e9-8e42-89f2d6fb7c31.gif)

**Comment by petschki** [comment]
I only have this behavior if I check "Narrow down filter options" ... otherwise it's counted as expected. I  do understand what the options technically does, but it's a bit confusing for the user. I've never activated it in my implementations. @thet you had an usecase for this?

**Comment by pigeonflight** [comment]
I've updated the bug report accordingly. At least the bug exists in only this edge case. I'm not sure that the count should vary when "Narrow down filter options" is enabled.
