### ISSUE TITLE
new release 3.1.0

### ISSUE THREAD

**Issue by petschki** [collective/collective.collectionfilter#50]
/cc @thet

**Comment by pigeonflight** [comment]
Can you review https://github.com/collective/collective.collectionfilter/pull/52
Which fixes #42

**Comment by petschki** [comment]
@thet i think we should release 3.1 ?

**Comment by thet** [comment]
@petschki @pigeonflight I want #61 to be reviewed first...

**Comment by thet** [comment]
Release on 2019-06-06
