### ISSUE TITLE
maps portlet prevents portlet manager loading in collective.geolocation not installed

### ISSUE THREAD

**Issue by djay** [collective/collective.collectionfilter#64]
you end up with a 404 on @@topbar-manage-portlets

Either needs another optional profile for geoloction or something more clever like a permission specifically for geolocation so the portlet only appears when its installed

**Comment by petschki** [comment]
is this fixed in the latest release? IIRC there's a merged PR from you related to this...

**Comment by djay** [comment]
Yes that pr fixed it

**Comment by djay** [comment]
fixed in https://github.com/collective/collective.collectionfilter/pull/67
