### ISSUE TITLE
Searching for only for non-alphanumeric characters causes exception

### ISSUE THREAD

**Issue by JeffersonBledsoe** [collective/collective.collectionfilter#86]
## Summary

Searching for only non-alphanumeric characters, such as `!` or `%` or `🙂`, throws the following exception: `ParseError: Query contains only common words: u'!*'`, where the `!` in `u'!*'` is the search string. This does not occur if alphanumeric characters are included in the search string.

## Steps to reproduce
- Add a collection search portlet
- In the search, search for "!"

## Expected result
- The results containing the character `!` are returned

## Actual result
- An ParseError exception is thrown

## Stack Trace
E.g. Searching for "!" produces the following stack trace:
```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module zope.browserpage.simpleviewclass, line 41, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 61, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 88, in __call__
  Module z3c.pt.pagetemplate, line 173, in render
  Module chameleon.zpt.template, line 306, in render
  Module chameleon.template, line 209, in render
  Module chameleon.template, line 187, in render
  Module 45d862eed365f94eae40d06a0f3d077a.py, line 1769, in render
  Module 377a257effc24713ae2f4b0305d3d73e.py, line 1028, in render_master
  Module 377a257effc24713ae2f4b0305d3d73e.py, line 345, in render_content
  Module 45d862eed365f94eae40d06a0f3d077a.py, line 1759, in __fill_content_core
  Module 45d862eed365f94eae40d06a0f3d077a.py, line 509, in render_content_core
  Module 45d862eed365f94eae40d06a0f3d077a.py, line 266, in render_listing
  Module Products.PageTemplates.expression, line 101, in __call__
  Module plone.app.contenttypes.browser.collection, line 47, in batch
  Module plone.app.contenttypes.browser.collection, line 42, in results
  Module plone.app.contenttypes.behaviors.collection, line 121, in results
  Module plone.app.querystring.querybuilder, line 98, in __call__
  Module plone.app.querystring.querybuilder, line 170, in _makequery
  Module Products.CMFPlone.CatalogTool, line 457, in searchResults
  Module Products.ZCatalog.ZCatalog, line 611, in searchResults
  Module Products.ZCatalog.Catalog, line 1091, in searchResults
  Module Products.ZCatalog.Catalog, line 634, in search
  Module Products.ZCatalog.Catalog, line 564, in _search_index
  Module Products.ZCTextIndex.ZCTextIndex, line 209, in query_index
  Module Products.ZCTextIndex.QueryParser, line 157, in parseQuery
ParseError: Query contains only common words: u'!*'

 - Expression: "view/batch"
 - Filename:   ... .egg/plone/app/contenttypes/browser/templates/listing.pt
 - Location:   (line 22: col 31)
 - Source:     <tal:results define="batch view/batch;
                                          ^^^^^^^^^^
 - Expression: "provider:plone.abovecontentbody"
 - Filename:   ... egg/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 94: col 70)
 - Source:     ... 
                                     ^
 - Expression: "context/@@main_template/macros/master"
 - Filename:   ... .egg/plone/app/contenttypes/browser/templates/listing.pt
 - Location:   (line 6: col 21)
 - Source:     ... tal:use-macro="context/@@main_template/macros/master"
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x1095ebe10>
               views: <ViewMapper - at 0x1108523d0>
               modules: <_SecureModuleImporter - at 0x104bc8650>
               args: <tuple - at 0x102f58050>
               here: <ImplicitAcquisitionWrapper testcollection at 0x10c50ff50>
               wrapped_repeat: <SafeMapping - at 0x1111cfcf8>
               user: <ImplicitAcquisitionWrapper - at 0x10c4c4960>
               nothing: <NoneType - at 0x102e7a718>
               container: <ImplicitAcquisitionWrapper testcollection at 0x10c50ff50>
               root: <ImplicitAcquisitionWrapper  at 0x10c5a58c0>
               request: <WSGIRequest - at 0x1110e7290>
               traverse_subpath: <list - at 0x10e9da638>
               default: <object - at 0x102fbb4a0>
               context: <ImplicitAcquisitionWrapper testcollection at 0x10c50ff50>
               view: <SimpleViewClass from /Users/jefferson/.buildout/eggs/plone.app.contenttypes-2.1.2-py2.7.egg/plone/app/contenttypes/browser/templates/listing.pt listing_view at 0x110852c10>
               translate: <function translate at 0x11071cc80>
               macroname: master
               options: {...} (0)
               loop: {...} (0)
               target_language: <NoneType - at 0x102e7a718>
```

**Comment by nngu6036** [comment]
* Investigation *

The search phrase is parsed by portal_catalog, with this pattern:
``` rxGlob_U = re.compile(r"\w+[\w*?]*", re.UNICODE) ```

https://github.com/plone/Products.CMFPlone/blob/58881a4b5a5e2de23f93557142fe45d048eaa2ae/Products/CMFPlone/UnicodeSplitter/config.py#L48

Search phrases contains only non-alphanumeric characters will throws exception:

* Option *

-  [ ] Leave it unchanged. Consider the need to search with only non-alphanumeric characters, is there a scenario for it
- [ ] Escape the non-alphanumeric characters and change the search pattern so that it allows alphanumeric character 
- [ ]  Display a nicer exception interface to user, for example, display an error message 'You need to have alphanumeric character in the search phrase'

@djay , please comment on the options

**Comment by djay** [comment]
@JeffersonBledsoe how does normal plone search deal with this? 
My guess is that the search should just ignore things it can't use but I'm not really sure. Displaying an error also seems reasonable.

**Comment by JeffersonBledsoe** [comment]
@djay The [previous comment on how the search phrase is being parsed](https://github.com/collective/collective.collectionfilter/issues/86#issuecomment-544372766) is correct. When [QueryParser comes to parsing the valid terms in an atom](https://github.com/zopefoundation/Products.ZCatalog/blob/e56ade80179e54b9d69b6296f8eedf3aa291ef72/src/Products/ZCTextIndex/Lexicon.py#L88-L93) , it calls `parseTerms` on the plone lexicon (as shown [here](https://github.com/zopefoundation/Products.ZCatalog/blob/e56ade80179e54b9d69b6296f8eedf3aa291ef72/src/Products/ZCTextIndex/Lexicon.py#L88-L93)), which proceeds to run each term in the search through the unicode splitter previously.

Plone's global search runs the exact same code, but it just catches the exception and returns no results:

https://github.com/plone/Products.CMFPlone/blob/719c685d65a2cdb577a157ca87e125e7a00dd7f5/Products/CMFPlone/browser/search.py#L77-L80

I think the likelihood of a user wanting to search for only non-alphanumeric characters is very low. Search queries seem to work correctly if you include characters which meet the regex so users can still refine searches with non-alphanumeric characters. Matching Plone's existing behaviour seems to be the right move here. If `Products.ZCTextIndex` had the ability to use double quotes to search for these kinds of characters then maybe returning results could be useful, but it doesn't so it would be a pretty useless endeavour right now.

**Comment by djay** [comment]
sure just do the same as what plone does

**Comment by JeffersonBledsoe** [comment]
> sure just do the same as what plone does

@djay How would you recommend getting the collection to return no results rather than everything like it currently does when it gets an invalid query?

**Comment by djay** [comment]
returning everything is also ok. the problem is returning an exception.

Seems to be its a collection bug not collection filter since if the user sets up a collection with a keyword term the same exception will be thrown. So thats one way is to do a PR on plone itself.

Since you can't change the search before it hits the collection I'm not sure its actually easy to fix in collectionfilter. I suspect a redirect would never get returned if the collection already raised an exception?
The only other hacky ways I can think of are
-  JS to alter the search before its posted?
- Is there some other way like a viewlet thats near the top of the page so we can later the request object?
- traversal hook that alters any request with SearchbleText in the url?
